"""Short acknowledgment phrases for zero-latency Piper cache."""

from __future__ import annotations

# Keep under ~140 chars so they hit the TTS cache path.
COMMON_PHRASES: tuple[str, ...] = (
    "Listo.",
    "Hecho.",
    "Entendido.",
    "Por supuesto.",
    "Dale.",
    "Ya.",
    "OK.",
    "Okey.",
    "Perfecto.",
    "Claro.",
    "Hecho, jefe.",
    "Listo, jefe.",
    "Entendido, jefe.",
    "Volumen ajustado.",
    "Volumen al treinta.",
    "Volumen al cincuenta.",
    "Volumen al setenta.",
    "Mute.",
    "Silenciado.",
    "Siguiente.",
    "Anterior.",
    "Pausa.",
    "Play.",
    "Abriendo.",
    "Abierto.",
    "Captura lista.",
    "Anotado.",
    "Asentado en el diario.",
    "Timer listo.",
    "Recordatorio guardado.",
    "Buscando.",
    "Un segundo.",
    "Ya vuelvo.",
    "No encontré nada.",
    "No hay nada para deshacer.",
    "Deshecho.",
    "Volumen restaurado.",
    "Portapapeles actualizado.",
    "Sin resultados.",
    "Hecho en el celular.",
    "Abriendo Spotify.",
    "Abriendo Chrome.",
    "Abriendo el mapa.",
    "Te escucho.",
    "Decime.",
    "¿En qué te ayudo?",
    "Estoy online.",
    "Todo bien.",
    "Permiso denegado.",
    "Eso es de la PC.",
)
